
1.a
```{r}
library(ggplot2)
set.seed(100)
n1 <- 10000
n2 <- 100
x <- matrix(rep(0, n1*n2), n1, n2)
for (j in 1:n2){
  for (i in 1:n1){
    x[i,j] <- runif(1, 0, 1)
  }
}
sum <- rowSums(x)
hist(sum)

a <- rnorm(100, 50, 100/12)
ggplot() + geom_density(aes(x=a), fill = "blue", adjust =2)+
  ylab("probability density")+
  xlab("x")+
  xlim(0, 100)

mean(sum)
sd(sum)
```





1.b
```{r}
set.seed(100)
n1 <- 10000
n2 <- 10
x <- matrix(rep(0, n1*n2), n1, n2)
y <- matrix(rep(0,n1, n1, 1))
for (i in 1:n1){
  for (j in 1:n2){
    x[i,j] <- runif(1, 0, 1)
    
  }
  y[i] <- sort(x[i,])[3]
}
hist(y)

a <- rbeta(10,3,8)
ggplot() + geom_density(aes(x=a), fill = "blue")+
  ylab("probability density")+
  xlab("x")+
  xlim(-.25, 0.5)
mean(y)
sd(y)
```

2
```{r}
set.seed(100)
n <- 10000
time <- rexp(n,10)
purchase <- rpois(n,10)
df <- data.frame(time, purchase)
hist(time)
hist(purchase)
```

3
```{r}
library(tidyverse)
library(FinancialMath)
n <- 10000 # number of trials
mr <- 115 #policy holders are expected to pay monthly
ny <- 20 # number of years in model
lump <- 1000000 #, the lumo that the beneficiaries expected to receive If a policy holder in good standing dies during the term of the policy
cancel_rate <- 0.003 # the rate that the policy holder will let the policy lapse 
cr <- 0.065 # the cost rate of the funds
x <- rweibull(n, 4.5, scale = 39)
m_cancel <- rexp(n, cancel_rate)
model <- rep(data.frame(), n)
npv <- rep(NULL, n)
function(x){
  for (i in 1:length(x)){
    year <- ny
    if(x[i]<ny)
      year <- x[i]
    model <- data.frame(1:year)
    model <- mutate(model, xx <- x[i],
                 revenue <-    )
  }
}

```

