1.
```{r}
library(EnvStats)
library(tidyverse)
library(ggplot2)
set.seed(100)

n <- 1000
x <- rdiscrete(n, probs=c(.35,.40,.20,.05), values=1:4)
a <- rdunif(n, 2000,5000)
b <- rdunif(n, 5001,10000)
c <- rdunif(n, 10001,14000)
d <- rdunif(n, 14001,15000)
demand <- case_when(x==1~a,
              x==2~b,
              x==3~c,
              x==4~d)

fc <- rnorm(n, 300, 60)
sales <- rep(NA, n)
nob <- c(4000, 8000, 12000, 15000) #number of boat
sim <- matrix(NA, n,length(nob) )
for(i in 1:length(nob)){
  tc <- fc + sum(rtri(nob[i], 77000, 100000, 90000))
  for (j in 1:n) {
    sales[j] <- min(demand[j], nob[i])
  }
  
  tr <- sales *150000 - tc
  for(k in 1:n){
    sim[k, i] <- tr[k]
  }
 
}

for(i in 1:length(nob)){
 cat("the mean of the total profit of selling ",nob[i],"boats is ", mean(sim[,i]), fill = TRUE )
  cat("the sd of the total profit of selling ",nob[i],"boats is ", sd(sim[,i]), fill = TRUE )
  hist(sim[,i], main = paste("Histogram of" , nob[i], "boats"))
}
# hist(sim[,1], main = paste("Histogram of" , nob[1], "boats"))
# hist(sim[,2], main = paste("Histogram of" , nob[2], "boats"))
# hist(sim[,3], main = paste("Histogram of" , nob[3], "boats"))
# hist(sim[,4], main = paste("Histogram of" , nob[4], "boats"))
```


#2
```{r}
library(tidyverse)
library(ggplot2)
library(MultiRNG)
library(Matrix)
library(matrixcalc)
library(fitdistrplus)
df <- read.csv("Assignment 3 Problem 1 data.csv")
hist(df$party_size, main = paste("Histogram of party size"))


dist_list_1<- c('norm','geom', "pois")

size_list<- lapply(X = dist_list_1,
                FUN = fitdist,
                data = df$party_size)
gofstat(size_list)

df<- df%>%mutate(
  ps = party_size -13
)
nps_list<- lapply(X = dist_list_1,
                FUN = fitdist,
                data = df$ps)
gofstat(nps_list)

nps.f <- fitdist(df$ps, "pois") |>print()

npsdist_list_2<- c('norm','lnorm',"gamma", 'weibull', 'logis', 'cauchy')
rev_list <- lapply(X = dist_list_2,
                FUN = fitdist,
                data = df$rev_per_person)
gofstat(rev_list)


rev.f <- fitdist(df$rev_per_person, "gamma") |>print()

qqcomp( fitdist(df$rev_per_person, "gamma"))
cdfcomp(fitdist(df$rev_per_person, "gamma"))

cor(df$party_size, df$rev_per_person)
```

#simulation
```{r}
n <- 100000
party <- rpois(n, 6.84) + 13
rev <- rgamma(n, 15.9386656, 0.0918413 )
df <- data.frame(party, rev)%>%mutate(
  tr = party*rev
)
 cat("the mean of the total revenue is ", mean(df$tr), fill = TRUE )
  cat("the sd of the total revenue is ", sd(df$tr), fill = TRUE )
  hist(df$tr)

```

